# Generated by Django 4.2.6 on 2024-03-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_author_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='user/%M/%y/%d'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birthy',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
